# Makefile for Mini-KVM (x86)
#
# Builds the VMM, the real-mode guest programs, and the 1K OS.
# Run the resulting binaries directly; see `make help`.

# --- Configuration ---
CC       := gcc
CFLAGS   := -Wall -Wextra -Wshadow -O2 -std=gnu11
CPPFLAGS := -MMD -MP
LDFLAGS  := -pthread
VMM      := kvm-vmm
BUILDDIR := build

# Every .c under src/, including the quarantined Linux boot support.
SRCS := $(wildcard src/*.c) $(wildcard src/linux/*.c)
OBJS := $(patsubst src/%.c,$(BUILDDIR)/%.o,$(SRCS))
DEPS := $(OBJS:.o=.d)

.DEFAULT_GOAL := help
.PHONY: all clean help vmm guests 1k-os examples test

# --- Build targets ---

all: vmm guests 1k-os examples
	@echo
	@echo "--- All components built ---"
	@echo "  ./kvm-vmm guest/hello"
	@echo "  ./kvm-vmm --paging os-1k/kernel"

vmm: $(VMM)

# Link. Object files carry their own header dependencies via -MMD, so there
# is no hand-maintained header list to fall out of date.
$(VMM): $(OBJS)
	@echo "=> Linking $@"
	@$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

$(BUILDDIR)/%.o: src/%.c
	@mkdir -p $(dir $@)
	@echo "=> Compiling $<"
	@$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

guests:
	@echo "=> Building real-mode guests..."
	@$(MAKE) --no-print-directory -C guest

1k-os:
	@echo "=> Building 1K OS..."
	@$(MAKE) --no-print-directory -C os-1k

# Third-party-style guests that use no Mini-KVM facilities. These are the
# real test of whether the VMM can run someone else's kernel.
examples:
	@echo "=> Building examples..."
	@$(MAKE) --no-print-directory -C examples/multiboot-barebones
	@$(MAKE) --no-print-directory -C examples/multiboot-keyboard
	@$(MAKE) --no-print-directory -C examples/multiboot2
	@$(MAKE) --no-print-directory -C examples/faults

# --- Verification ---

# There is no unit test suite: tools/smoke.sh runs every guest path and diffs
# the output against a stored baseline. Requires /dev/kvm.
test: all
	@./tools/smoke.sh

# --- Cleanup ---

clean:
	@echo "=> Cleaning..."
	@rm -rf $(BUILDDIR) $(VMM)
	@$(MAKE) --no-print-directory -C guest clean
	@$(MAKE) --no-print-directory -C os-1k clean
	@$(MAKE) --no-print-directory -C examples/multiboot-barebones clean
	@$(MAKE) --no-print-directory -C examples/multiboot-keyboard clean
	@$(MAKE) --no-print-directory -C examples/multiboot2
	@$(MAKE) --no-print-directory -C examples/multiboot2 clean
	@$(MAKE) --no-print-directory -C examples/faults clean
	@echo "Done."

# --- Help ---

help:
	@echo "Mini-KVM build system"
	@echo
	@echo "Targets:"
	@echo "  all        Build the VMM, guests, and 1K OS"
	@echo "  vmm        Build only the VMM"
	@echo "  guests     Build only the real-mode guests"
	@echo "  1k-os      Build only the 1K OS"
	@echo "  examples   Build the example Multiboot kernel"
	@echo "  test       Build, then run tools/smoke.sh (needs /dev/kvm)"
	@echo "  clean      Remove all build artifacts"
	@echo
	@echo "Running:"
	@echo "  ./kvm-vmm guest/hello                     Real mode, one vCPU"
	@echo "  ./kvm-vmm guest/counter guest/hello       One guest per vCPU (max 4)"
	@echo "  ./kvm-vmm --paging os-1k/kernel           1K OS interactive shell"
	@echo "  ./kvm-vmm --long-mode guest/hello_64      64-bit long mode"
	@echo "  ./kvm-vmm --vga examples/multiboot-barebones/kernel.elf"
	@echo "                                            A stock Multiboot kernel"
	@echo "  ./kvm-vmm --help                          All options"
	@echo
	@echo "Scripted 1K OS runs (piped stdin skips raw mode, so these are"
	@echo "deterministic; input ends the guest at EOF):"
	@echo "  printf '1\\n0\\n'             | ./kvm-vmm --paging os-1k/kernel"
	@echo "  printf '6\\n10 + 5\\nq\\n0\\n' | ./kvm-vmm --paging os-1k/kernel"

# Header dependencies generated by -MMD.
-include $(DEPS)
